### ISSUE TITLE
Peer-to-peer-review (David-Dennis-Sergio-Sam)

### ISSUE THREAD

**Issue by denscholar** [sergiogval/sergiogval.github.io#9]
You did awesomely great; however, it could be nice if you implement ES6 syntax (Arrow function to be precise) when constructing your function. For instance, 
```
Instead of this:
function saveLocalStore() {
            const data = {
              name: nameI.value,
              email: emails.value,
              message: message.value,
            }; 

Do this:

const saveLocalStore = () => {
 const data = {
    name: nameI.value,
    email: emails.value,
    message: message.value,
  };

```
<img src="https://media2.giphy.com/media/tEXeL9FRm6PAI/giphy.gif"/>

[review](https://github.com/sergiogval/temporal-portfolio-repo/commit/73561cb79b4b3560dc49d6229b028177e7499cd8#diff-b6ab94beaac0b6a0430f245fc1b3fb16e2abf7b8c4b84c68b3829bc30a45e4b1R1-R26)

**Comment by sergiogval** [comment]
- [ ] TODO

**Comment by sergiogval** [comment]
Done
